### ISSUE TITLE
Using super_annotations with source_gen

### ISSUE THREAD

**Issue by bluegearapps** [schultek/super_annotations#2]
I am using source_gen to generate other .g.dart files (for model generation and json serialization). Now I am adding super_annotations for static metaprogramming. When I run the command it throws error:

```
Both source_gen:combining_builder and super_annotations:super_annotations may output lib/main_libra_cart.g.dart. Potential outputs must be unique across all builders. See https://github.com/dart-lang/build/blob/master/docs/faq.md#why-do-builders-need-unique-outputs
```
Based on my understanding, following the guide above, I have to add new build.yaml config, with `generate_for`

From source_gen:
```
The combining builder reads in all the pieces written by different shared part builders and writes them to the final .g.dart output in the user's source directory. You should never use the .g.dart extension for any other Builder.
```

How to modify the ouput so the don't have conflict? Thank you!

**Comment by schultek** [comment]
I published a fix in version `0.3.7` for this.
To resolve the conflict, you have to define a custom target for `super_annotations` in your `build.yaml`:
```yaml
global_options:
  super_annotations:
    options:
      targets: [ mytarget ]
```

This will then generate `main.mytarget.dart` instead of `main.g.dart` and therefore should not have any conflict with source_gen.

**Comment by bluegearapps** [comment]
Thank you so much for your answer, I have a build.yaml only includes differrent files for different builders, and that resolved the issue

```
targets:
  $default:
    builders:
      built_value_generator|built_value:
        generate_for:
          include:
            - lib/models/**.dart
      source_gen|combining_builder:
        generate_for:
          include:
            - lib/models/**.dart
      super_annotations:
        generate_for:
          include:
            - lib/display_models/**.dart
```
    
I have one class `DisplayAnnotation` extends `ClassAnnotation`
And use the annotation in 3 other classes, using mixin, very similar to this example https://github.com/schultek/super_annotations/tree/main/examples/part_of_strategy

`class_a.dart` file:
```dart
@CodeGen(runAfter: [CodeGen.addPartOfDirective])
library test1;

part 'class_a.g.dart';

class ClassA extends StatefulWidget{
  @override
  State<StatefulWidget> createState() {
    return ClassAState();
  }
}

@ DisplayAnnotation(
    name: 'Test1',
)
class ClassAState extends State<ClassA> with _$ClassAState{
  @override
  void initState(){
    generatedInitState();
    super.initState();
}

```
and `class_b.dart` file:

```dart
@CodeGen(runAfter: [CodeGen.addPartOfDirective])
library test2;

part 'class_b.g.dart';

class ClassB extends StatefulWidget{
  @override
  State<StatefulWidget> createState() {
    return ClassBState();
  }
}

@ DisplayAnnotation(
    name: 'Test2',
)
class ClassBState extends State<ClassB> with _$ClassBState{
  @override
  void initState(){
    generatedInitState();
    super.initState();
}

```
and `class_c.dart` file:

```dart
@CodeGen(runAfter: [CodeGen.addPartOfDirective])
library test3;

part 'class_c.g.dart';

class ClassC extends StatefulWidget{
  @override
  State<StatefulWidget> createState() {
    return ClassCState();
  }
}

@ DisplayAnnotation(
    name: 'Test3',
)
class ClassCState extends State<ClassC> with _$ClassCState{
  @override
  void initState(){
    generatedInitState();
    super.initState();
}

```

After running the build command: `flutter packages pub run build_runner build --delete-conflicting-outputs`
The .g.dart files are generated, each file *has all the contents* of other files: class_a.g.dart has content of class_b.g.dart and class_c.g.dart, also class_b.g.dart has all content of class_a.g.dart and class_c.g.dart,

Do you have any idea about this issue?
